test

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -43,18 +43,27 @@ else
 fi
 
 if [ ! "$SKIP_INSTALL" ]; then
-    puts-step "Installing $PYTHON_VERSION"
+  puts-step "Installing $PYTHON_VERSION"
 
-    # Prepare destination directory.
-    mkdir -p .heroku/python
+  # Prepare destination directory.
+  mkdir -p .heroku/python
 
-    mcount "version.python.$PYTHON_VERSION"
+  mcount "version.python.$PYTHON_VERSION"
 
-    if ! curl "${VENDORED_PYTHON}" -s | tar zxv -C .heroku/python &> /dev/null; then
-      puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
-      puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
-      exit 1
-    fi
+  # Use system python, if the version matches
+  echo "$SYSTEM_PYTHON" -- "$SYSTEM_PYTHON_VERSION" -- "$PYTHON_VERSION"
+  if [[ -f "$SYSTEM_PYTHON" ]] && [[ "$SYSTEM_PYTHON_VERSION" == "$PYTHON_VERSION" ]]; then
+    puts-step "Using system-installed $SYSTEM_PYTHON"
+    mkdir -p "$BUILD_DIR/.heroku/python/bin" "$BUILD_DIR/.heroku/python/lib"
+    ln -nsf "$SYSTEM_PYTHON" "$BUILD_DIR/.heroku/python/bin/python3"
+    ln -nsf "$SYSTEM_PYTHON" "$BUILD_DIR/.heroku/python/bin/python"
+    # ln -nsf "$BUILD_DIR/.heroku/python" "$HOME/.local"
+
+  elif ! curl "${VENDORED_PYTHON}" -s | tar zxv -C .heroku/python &> /dev/null; then
+    puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
+    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+    exit 1
+  fi
 
   # Record for future reference.
   echo "$PYTHON_VERSION" > .heroku/python-version
@@ -64,8 +73,20 @@ if [ ! "$SKIP_INSTALL" ]; then
   hash -r
 fi
 
+# On Heroku CI, builds happen in `/app`. Otherwise, on the Heroku platform,
+# they occur in a temp directory. Beacuse Python is not portable, we must create
+# symlinks to emulate that we are operating in `/app` during the build process.
+# This is (hopefully obviously) because apps end up running from `/app` in production.
+if [[ "$BUILD_DIR" != '/app' ]]; then
+    mkdir -p /app
+    ln -nsf "$BUILD_DIR/.heroku" /app/.heroku
+    # ln -nsf "$BUILD_DIR/.heroku/python" /app/.heroku/python
+    # ln -nsf "$BUILD_DIR/.heroku/vendor" /app/.heroku/vendor
+fi
 
 # If Pip isn't installed:
+export PYTHONUSERBASE="$BUILD_DIR/.heroku/python"
+INSTALLED_PYTHON="/app/.heroku/python/bin/python"
 if [ "$FRESH_PYTHON" ] || [[ ! -f "$BUILD_DIR/.heroku/python/bin/pip" ]]; then
 
   puts-step "Installing pip"
@@ -74,8 +95,23 @@ if [ "$FRESH_PYTHON" ] || [[ ! -f "$BUILD_DIR/.heroku/python/bin/pip" ]]; then
   rm -fr "$BUILD_DIR/.heroku/python/lib/python*/site-packages/pip-*"
   rm -fr "$BUILD_DIR/.heroku/python/lib/python*/site-packages/setuptools-*"
 
-  "$BUILD_DIR/.heroku/python/bin/python" "$ROOT_DIR/vendor/get-pip.py" pip=="$PIP_UPDATE" &> /dev/null
-  "$BUILD_DIR/.heroku/python/bin/pip" install "$ROOT_DIR/vendor/setuptools-39.0.1-py2.py3-none-any.whl" &> /dev/null
+  ls -la "$BUILD_DIR/.heroku/python"; echo
+  ls -la "$BUILD_DIR/.heroku/python/bin"; echo
+  ls -la "$BUILD_DIR/.heroku/python/lib"; echo
+  echo; echo;
+  which -a pip
+
+  # Installed via symlinks to maintain python-path
+  "$INSTALLED_PYTHON" "$ROOT_DIR/vendor/get-pip.py" pip=="$PIP_UPDATE" --user
+
+  ls -la "/app/.heroku/python"; echo
+  ls -la "/app/.heroku/python/bin"; echo
+  ls -la "/app/.heroku/python/lib"; echo
+  echo; echo;
+  which -a pip
+  printenv
+  "$BUILD_DIR/.heroku/python/bin/pip" install -U pip
+  "$BUILD_DIR/.heroku/python/bin/pip" install "$ROOT_DIR/vendor/setuptools-39.0.1-py2.py3-none-any.whl"
 
 fi
 
